

title: NVfastplease
author: Nicholas Valentinus

baseurl: /demo
url: https://nvfp.github.io


include: [_sass, pages]

sass:
  style: compact  # possible values: nested expanded compact compressed
  sass_dir: _sass

plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from


permalink: /:categories/:title.html
