jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        shell: python
        run: |
          ## github.event.head_commit.message must not contain single quotes
          x = '${{ github.event.head_commit.message }}'

          ## github.event.head_commit.message must not contain double quotes
          x = "${{ github.event.head_commit.message }}"

          ## github.event.head_commit.message must not contain """
          x = """${{ github.event.head_commit.message }}"""