# A clean way to chain jobs (shell: python)

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      match: ${{ steps.run.outputs.match }}
    steps:
      - name: Run
        id: run
        shell: python
        run: |
          import os

          # If the code below is not executed, `job2` will be skipped.
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            print(f'match=true', file=f)  # This makes `job2` to run
            # print(f'match={True}', file=f)  # Also this
            # print(f'match={False}', file=f)  # Also this
            # print(f'match=YEAH!', file=f)  # Also this

  job2:
    needs: check
    if: needs.check.outputs.match
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "Hi"