name: test gh action log grouping

on:
  push:
    branches:
      - main

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Foo
        run: |
          echo "abc"


          echo "::group::group1"

          echo "Hello"
          
          echo "::group::group2"
          echo "World"
          echo "::endgroup::"

          echo "Foo"
          
          echo "::group::group3"
          echo "Bar"
          echo "::endgroup::"

          echo "Baz"
          
          echo "::endgroup::"


          echo "xyz"