name: test using gh action cache

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: |
          echo "${{ runner.os }}"
          echo "${{ env.cache-name }}"