name: Test pypi package

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          url="https://pypi.org/project/for-testing/22.1.1/"
          status_code=$(curl -s -o /dev/null -w "%{http_code}" $url)
          echo $status_code

          url="https://pypi.org/project/for-testing/22.1.1000/"
          status_code=$(curl -s -o /dev/null -w "%{http_code}" $url)
          echo $status_code