name: Test Simple release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: nvfp/gh-action-simple-release@1.13.0
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          tag: 47.10.200b321c
          desc: 'Testing nvfp/gh-action-simple-release v1.13.0: Invalid tag'