name: test using gh action cache

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Create
        run: |
          echo "+++"
          ls
          echo "---"
          
          echo "foo123" > abcxyz.txt
          
          echo "+++"
          ls
          echo "---"