name: "Testing nvfp/gh-action-simple-release"

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release
        uses: nvfp/gh-action-simple-release@1.4.0
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          tag: 10.20.300
          desc: Test release using `nvfp/gh-action-simple-release@1.4.0`