name: "Testing nvfp/gh-action-simple-release"

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Releasing
        uses: nvfp/gh-action-simple-release@1.3.0
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          tag: 300.200.100
          desc: Test release using `nvfp/gh-action-simple-release@1.3.0`