name: test bringing a file across branches

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 1
        run: |
          echo "---pwd: '$(pwd)'"
          ls
          cd ..
          echo "---pwd: '$(pwd)'"
          ls
      - uses: actions/checkout@v3
      - name: run
        run: |
          echo "pwd: '$(pwd)'"
          ls
          cd ..
          echo "pwd: '$(pwd)'"
          ls
          cd demo
          echo "pwd: '$(pwd)'"
          ls
          python test-dir/test.py
          echo "--------"
          ls
          cd ..
          echo "pwd: '$(pwd)'"
          ls
          echo "====="
          ls arch_temp
      - uses: actions/checkout@v3
        with:
          ref: web-download-button
      - name: foo
        run: |
          echo "pwd: '$(pwd)'"
          ls
          cat $(pwd)/../arch_temp/foobarbaz321.txt

          mv $(pwd)/../arch_temp/foobarbaz321.txt .
          echo "pwd: '$(pwd)'"
          ls

          git config user.name "test bringing file across branches"
          git config user.email "asjdovheoiefbaeoecbsa@email"
          git add .
          git commit -m "test bringing file across branches"
          git push