name: "Testing nvfp/gh-action-simple-release"

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message
        uses: nvfp/gh-action-simple-release@1.2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag: 100.200.300
          desc: Test release