name: test using gh action cache

on:
  push:
    branches:
      - main

env:
  CACHE_DIR: mycache123-v1
  MY_TEST_PY_VENV: "MY_TEST_VENV_8"

jobs:
  job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Try restore
        uses: actions/cache/restore@v3
        id: restore-cache
        with:
          path: |
            ${{ env.MY_TEST_PY_VENV }}
          key: key-${{ env.MY_TEST_PY_VENV }}
      
      - name: Cache found
        if: steps.restore-cache.outputs.cache-hit == 'true'
        run: |
          echo "pwd: '$(pwd)'"
          echo "+++"
          ls
          echo "---"

          source $MY_TEST_PY_VENV/bin/activate
          which python
    
      - name: Cache not found
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          echo "pwd: '$(pwd)'"
          echo "MY_TEST_PY_ENV: '$$MY_TEST_PY_ENV'"
          echo "+++"
          ls
          echo "---"
          
          python -m venv $MY_TEST_PY_VENV
          echo "+++"
          ls
          echo "---"

          # chmod +x $MY_TEST_PY_VENV/bin/activate  # it requires permission to be executed; but no if using 'source ' in `source $MY_TEST_PY_VENV/bin/activate`
          source $MY_TEST_PY_VENV/bin/activate
          which python
          # pip list
          # echo "==="
          # pip install numpy
          # echo "==="
          # pip list
          echo "::group::py"
          # pip install -r requirements.txt 
          echo "::endgroup::"

          echo "::group::ff"
          # sudo apt update
          # sudo apt install ffmpeg
          echo "::endgroup::"

          echo "+++ff"
          # which ffmpeg
          echo "+++ff"

          echo "MY_TEST_PY_ENV: '$$MY_TEST_PY_ENV'"
          echo "----"
          ls "$MY_TEST_PY_ENV"
          echo "----"
          sudo mv $(which ffmpeg) $(pwd)/$MY_TEST_PY_ENV/FFMPEG_CACHED
          echo "----"
          ls "$MY_TEST_PY_ENV"
          echo "----"
      
      - name: Cache not found -> Save the cache 
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            ${{ env.MY_TEST_PY_VENV }}
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
    
      - name: Run
        run: |
          which python
          source $MY_TEST_PY_VENV/bin/activate
          which python
          python test-dir/testpy.py 

          echo "MY_TEST_PY_ENV: '$$MY_TEST_PY_ENV'"

          $MY_TEST_PY_ENV/ffmpeg
          echo "---"
          ffmpeg
      


    ## Test setup-python caching (not sure how to use it)
    # steps:
    #   - uses: actions/checkout@v3 
    #   - uses: actions/setup-python@v4
    #     with:
    #       python-version: '3.9'
    #       cache: 'pip' # caching pip dependencies 

    #   - name: try
    #     shell: python
    #     run: |
    #       import numpy as np
    #       print(np.array)

    #   - run: pip install -r requirements.txt



    # Test caching a simple file
    # steps:
    #   - name: debug
    #     run: |
    #       echo "cache-dir: $CACHE_DIR"

    #       echo "pwd: '$(pwd)'"
    #       echo "+++"
    #       ls
    #       echo "---"

    #   - uses: actions/cache/restore@v3
    #     id: restore-cache
    #     with:
    #       path: |
    #         ${{ env.CACHE_DIR }}
    #       key: key-${{ env.CACHE_DIR }}
    
    #   - name: print cache-hit
    #     run: |
    #       echo "cache-hit: '${{ steps.restore-cache.outputs.cache-hit }}'"
      
    #   - name: Cache found
    #     if: steps.restore-cache.outputs.cache-hit == 'true'
    #     run: |
    #       echo "pwd: '$(pwd)'"
    #       echo "+++"
    #       ls
    #       echo "---"
    #       cd $CACHE_DIR
    #       cat foo123.txt
    
    #   - name: Cache not found
    #     if: steps.restore-cache.outputs.cache-hit != 'true'
    #     run: |
    #       echo "pwd: '$(pwd)'"
    #       echo "+++"
    #       ls
    #       echo "---"
          
    #       mkdir $CACHE_DIR
    #       echo "+++"
    #       ls
    #       echo "---"
          
    #       cd $CACHE_DIR
    #       echo "+++"
    #       ls
    #       echo "---"
          
    #       echo "foo bar-baz_123" > foo123.txt
    #       echo "+++"
    #       ls
    #       echo "---"

    #       cd ..

    #   - uses: actions/cache/save@v3
    #     with:
    #       path: |
    #         ${{ env.CACHE_DIR }}
    #       key: ${{ steps.restore-cache.outputs.cache-primary-key }}