name: "Test run Py script from .sh"

on:
  push:
    branches:
      - main

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "pwd: '$(pwd)'"
          ls