# Testing repo cloning with specific git tag and GitHub Actions version

name: testing..

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cloning
        run: |
          git clone --depth 1 --branch 1.0.0 https://github.com/nvfp/demo-testing.git
          echo "---"
          cd demo-testing
          ls
          echo "---"
          git log

      - name: cloning a nonexistent tag
        run: |
          cd ..
          ls
          rm -r demo-testing
          echo "---"
          git clone --depth 1 --branch 3.0.0 https://github.com/nvfp/demo-testing.git
          echo "---"
          cd demo-testing
          ls
          echo "---"
          git log

      - name: gh-action
        uses: nvfp/demo-testing@1.0.0
        with:
          foo: 3.2.1
          bar: 'Foo: bar baz baz'

      - name: gh-action 2.0.0
        uses: nvfp/demo-testing@2.0.0
        with:
          foo: foo bar
          bar: 'a\nb\nc foo'