name: Testing Publish on release commit

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.validate.outputs.status }}
      version: ${{ steps.validate.outputs.version }}

    steps:
    - id: validate
      name: Check commit message
      env:
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      run: |
        echo "Commit message: $COMMIT_MESSAGE"
        regex="^([0-9]+\.[0-9]+\.[0-9]+) Release.*"
        if [[ $COMMIT_MESSAGE =~ $regex ]]; then 
          echo "INFO: Pattern matched."
          ver="${BASH_REMATCH[1]}"
          echo "INFO: Version: $ver"
          echo "status=success" >> $GITHUB_OUTPUT
          echo "version=$ver" >> $GITHUB_OUTPUT
        else
          echo "INFO: Pattern doesn't match."
          echo "status=fail" >> $GITHUB_OUTPUT
        fi

  work:
    needs: check
    if: needs.check.outputs.status == 'success'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Match version
      run: |
        echo "version: ${{ needs.check.outputs.version }}"
        
        files=$(find docs -iname "*changelog*")
        echo "files: $files"

        # Check if any matching files are found
        if [ -n "$files" ]; then
          # Print the content of each matching file
          for file in $files; do
            echo "=== $file ==="
            cat "$file"
          done
        else
          # Exit with exit code 1 if no matching files are found
          exit 1
        fi

        echo "foo"