name: Testing
on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: step1
        run: |
          echo "step1"
          # echo "foo=true" >> $GITHUB_OUTPUT

      - name: step2
        id: step2
        if: steps.step1.outputs.foo
        run: |
          echo "step2"

      - name: step3
        if: steps.step2.outcome == 'success'
        run: |
          echo "step3"