name: the A

on:
  push:
    branches:
      - main

jobs:
  work-A:
    runs-on: ubuntu-latest
    steps:
      - name: The A
        run: |
          echo "aaa"
          for i in {0..9}; do
            echo $i
            sleep 1
          done